#pragma once
#include <iostream>
#include <Windows.h>
#include <TlHelp32.h>
#include <vector>
#include <Psapi.h>
#include <cstring>
#include <array>
#include <thread>
#include <iterator>
#include <math.h>
#include <fstream>
#include <vector>
#include <iostream>
#include <stdexcept>
#include <filesystem>
#include <stdio.h>
#include <string>